name: First Workflow
on: workflow_dispatch  # manual trigger
jobs:
  first-job:  # name of first job
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello World!"
      - name: print goodbye
        run: echo "Done - bye!"
